"""empty message

Revision ID: ca7f3163a6e9
Revises: 4691e574f204
Create Date: 2017-07-13 10:51:49.814473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca7f3163a6e9'
down_revision = '4691e574f204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mannschaften',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('positionen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spielers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('vorname', sa.String(length=60), nullable=True),
    sa.Column('nachname', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('mannschaft_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mannschaft_id'], ['mannschaften.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positionen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spielers_email'), 'spielers', ['email'], unique=True)
    op.create_index(op.f('ix_spielers_nachname'), 'spielers', ['nachname'], unique=False)
    op.create_index(op.f('ix_spielers_username'), 'spielers', ['username'], unique=True)
    op.create_index(op.f('ix_spielers_vorname'), 'spielers', ['vorname'], unique=False)
    op.drop_table('employees')
    op.drop_table('departments')
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('departments',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('employees',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], [u'departments.id'], name=u'employees_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], name=u'employees_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_spielers_vorname'), table_name='spielers')
    op.drop_index(op.f('ix_spielers_username'), table_name='spielers')
    op.drop_index(op.f('ix_spielers_nachname'), table_name='spielers')
    op.drop_index(op.f('ix_spielers_email'), table_name='spielers')
    op.drop_table('spielers')
    op.drop_table('positionen')
    op.drop_table('mannschaften')
    # ### end Alembic commands ###
